import { SourceConfigSchema, type SourceConfig } from "@allabout/contracts";

import { demo101Sources } from "./demo101-fixtures.js";

const candidateSources = [
  {
    id: "academic-calendar-csc207",
    kind: "official",
    label: "A&S Academic Calendar — CSC207H1",
    entryUrl: "https://artsci.calendar.utoronto.ca/course/csc207h1",
    allowedHosts: ["artsci.calendar.utoronto.ca"],
    scope: {
      school: "University of Toronto",
      campus: "UTSG",
      term: null,
      course: "CSC207H1",
      section: null,
      entity: null,
    },
    contentMode: "live",
    access: "public",
  },
  {
    id: "academic-calendar-csc148",
    kind: "official",
    label: "A&S Academic Calendar — CSC148H1",
    entryUrl: "https://artsci.calendar.utoronto.ca/course/csc148h1",
    allowedHosts: ["artsci.calendar.utoronto.ca"],
    scope: {
      school: "University of Toronto",
      campus: "UTSG",
      term: null,
      course: "CSC148H1",
      section: null,
      entity: null,
    },
    contentMode: "live",
    access: "public",
  },
  {
    id: "uoft-events",
    kind: "official",
    label: "University of Toronto Events",
    entryUrl: "https://www.utoronto.ca/events",
    allowedHosts: ["www.utoronto.ca"],
    scope: {
      school: "University of Toronto",
      campus: "UTSG",
      term: null,
      course: null,
      section: null,
      entity: null,
    },
    contentMode: "live",
    access: "public",
  },
  {
    id: "alumni-carillon-recital",
    kind: "official",
    label: "U of T Alumni — Labour Day Carillon Recital",
    entryUrl: "https://alumni.utoronto.ca/events/labour-day-carillon-recital-0",
    allowedHosts: ["alumni.utoronto.ca"],
    scope: {
      school: "University of Toronto",
      campus: "UTSG",
      term: null,
      course: null,
      section: null,
      entity: "Labour Day Carillon Recital",
    },
    contentMode: "live",
    access: "public",
  },
  {
    id: "academic-calendar-sessional-dates",
    kind: "official",
    label: "A&S Academic Calendar — Sessional Dates",
    entryUrl: "https://artsci.calendar.utoronto.ca/sessional-dates",
    allowedHosts: ["artsci.calendar.utoronto.ca"],
    scope: {
      school: "University of Toronto",
      campus: "UTSG",
      term: null,
      course: null,
      section: null,
      entity: null,
    },
    contentMode: "live",
    access: "public",
  },
  {
    id: "cs-undergrad-courses",
    kind: "official",
    label: "CS Department — Undergraduate courses",
    entryUrl: "https://web.cs.toronto.edu/undergraduate/courses",
    allowedHosts: ["web.cs.toronto.edu"],
    scope: {
      school: "University of Toronto",
      campus: "UTSG",
      term: null,
      course: null,
      section: null,
      entity: null,
    },
    contentMode: "live",
    access: "public",
  },
  {
    id: "reddit-uoft-csc207",
    kind: "community",
    label: "Reddit r/UofT",
    entryUrl: "https://old.reddit.com/r/UofT/",
    allowedHosts: ["old.reddit.com", "www.reddit.com"],
    scope: {
      school: "University of Toronto",
      campus: "UTSG",
      term: null,
      course: "CSC207H1",
      section: null,
      entity: null,
    },
    contentMode: "live",
    access: "public",
  },
  {
    id: "reddit-uoft",
    kind: "community",
    label: "Reddit r/UofT",
    entryUrl: "https://old.reddit.com/r/UofT/",
    allowedHosts: ["old.reddit.com", "www.reddit.com"],
    scope: {
      school: "University of Toronto",
      campus: "UTSG",
      term: null,
      course: null,
      section: null,
      entity: null,
    },
    contentMode: "live",
    access: "public",
  },
  {
    id: "piazza-login",
    kind: "course_discussion",
    label: "Piazza class discussion",
    entryUrl: "https://piazza.com/login",
    allowedHosts: ["piazza.com"],
    scope: {
      school: "University of Toronto",
      campus: "UTSG",
      term: null,
      course: null,
      section: null,
      entity: null,
    },
    contentMode: "live",
    access: "authorized",
  },
  {
    id: "artsci-exam-conflicts",
    kind: "official",
    label: "A&S Final Exam Conflicts",
    entryUrl:
      "https://www.artsci.utoronto.ca/current/faculty-registrar/final-exams/exam-conflicts",
    allowedHosts: ["www.artsci.utoronto.ca", "artsci.calendar.utoronto.ca"],
    scope: {
      school: "University of Toronto",
      campus: "UTSG",
      term: null,
      course: null,
      section: null,
      entity: "final-exams",
    },
    contentMode: "live",
    access: "public",
  },
  {
    id: "hart-house-events",
    kind: "official",
    label: "Hart House events",
    entryUrl: "https://harthouse.ca/events/month",
    allowedHosts: ["harthouse.ca", "www.utoronto.ca"],
    scope: {
      school: "University of Toronto",
      campus: "UTSG",
      term: null,
      course: null,
      section: null,
      entity: null,
    },
    contentMode: "live",
    access: "public",
  },
  {
    id: "student-life-events",
    kind: "official",
    label: "Student Life events",
    entryUrl: "https://www.studentlife.utoronto.ca/events/",
    allowedHosts: ["www.studentlife.utoronto.ca"],
    scope: {
      school: "University of Toronto",
      campus: "UTSG",
      term: null,
      course: null,
      section: null,
      entity: null,
    },
    contentMode: "live",
    access: "public",
  },
  {
    id: "artsci-academic-dates",
    kind: "official",
    label: "A&S academic dates",
    entryUrl: "https://www.artsci.utoronto.ca/current/dates-deadlines/academic-dates",
    allowedHosts: ["www.artsci.utoronto.ca", "artsci.calendar.utoronto.ca"],
    scope: {
      school: "University of Toronto",
      campus: "UTSG",
      term: null,
      course: null,
      section: null,
      entity: null,
    },
    contentMode: "live",
    access: "public",
  },
  {
    id: "timetable-builder",
    kind: "official",
    label: "Timetable Builder",
    entryUrl: "https://ttb.utoronto.ca/",
    allowedHosts: ["ttb.utoronto.ca"],
    scope: {
      school: "University of Toronto",
      campus: "UTSG",
      term: null,
      course: null,
      section: null,
      entity: null,
    },
    contentMode: "live",
    access: "public",
  },
  {
    id: "the-varsity-about",
    kind: "community",
    label: "The Varsity",
    entryUrl: "https://thevarsity.ca/about/",
    allowedHosts: ["thevarsity.ca"],
    scope: {
      school: "University of Toronto",
      campus: "UTSG",
      term: null,
      course: null,
      section: null,
      entity: null,
    },
    contentMode: "live",
    access: "public",
  },
  {
    id: "ulife-organizations",
    kind: "official",
    label: "ULife organizations",
    entryUrl: "https://www.ulife.utoronto.ca/organizations",
    allowedHosts: ["www.ulife.utoronto.ca", "www.studentlife.utoronto.ca"],
    scope: {
      school: "University of Toronto",
      campus: "UTSG",
      term: null,
      course: null,
      section: null,
      entity: null,
    },
    contentMode: "live",
    access: "public",
  },
  {
    id: "quercus-login",
    kind: "official",
    label: "Quercus",
    entryUrl: "https://q.utoronto.ca/",
    allowedHosts: ["q.utoronto.ca"],
    scope: {
      school: "University of Toronto",
      campus: "UTSG",
      term: null,
      course: null,
      section: null,
      entity: null,
    },
    contentMode: "live",
    access: "authorized",
  },
  {
    id: "acorn-login",
    kind: "official",
    label: "ACORN",
    entryUrl: "https://www.acorn.utoronto.ca/",
    allowedHosts: ["www.acorn.utoronto.ca"],
    scope: {
      school: "University of Toronto",
      campus: "UTSG",
      term: null,
      course: null,
      section: null,
      entity: null,
    },
    contentMode: "live",
    access: "authorized",
  },
  ...demo101Sources,
] satisfies SourceConfig[];

export const liveSourceRegistry = SourceConfigSchema.array()
  .min(1)
  .parse(candidateSources);
