import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUp,ArrowDown,ArrowUpRight,ArrowRight,Check,ChevronDown,ChevronLeft,ChevronRight,Globe,MessageSquare,Monitor,Plus,Square,FileText,BookOpen,History,Search,X,SlidersHorizontal,Trash2,RotateCcw,LoaderCircle,Link2,Clock3,ExternalLink} from 'lucide-react';
import {readHistory,readPreferences,classify,visitedSources,HISTORY_KEY,SETTINGS_KEY,type Run,type Preferences} from './history';
import './desk.css';

const sources=[
 {title:'Course syllabus',path:'demo101 / syllabus',host:'courses.campus-demo.test',role:'Course document',date:'Sep 1, 2026',quote:'Assignment 2 is due September 18, 2026 at 5:00 PM (America/Toronto). Submit your work as a single PDF.',note:'Original deadline. Updated by the instructor announcement.',icon:FileText},
 {title:'Assignment 2 — deadline update',path:'demo101 / announcements / a2',host:'courses.campus-demo.test',role:'Instructor announcement',date:'Sep 12, 2026',quote:'The deadline for Assignment 2 has been extended to September 20, 2026 at 5:00 PM (America/Toronto). All other submission requirements remain unchanged.',note:'An explicit extension for the same assignment and term.',icon:BookOpen},
 {title:'Thoughts on last year’s assignment',path:'demo101 / discussion / a2',host:'discussion.campus-demo.test',role:'Student discussion',date:'Sep 10, 2026',quote:'Last year this assignment felt manageable. I remember handing it in on a Friday.',note:'Previous-year experience, not a course policy.',icon:MessageSquare},
];
const activity=[
 {title:'Looking for the right sources',detail:'Campus search · DEMO101 · Assignment 2',source:null},
 {title:'Reading the course syllabus',detail:sources[0].host,source:0},
 {title:'Checking the instructor’s update',detail:sources[1].host,source:1},
 {title:'Reading the student discussion',detail:sources[2].host,source:2},
 {title:'Comparing dates and citations',detail:'Same course · same term · same assignment',source:null},
 {title:'Answer ready',detail:'3 demo pages reviewed · citations attached',source:null},
];
const starterQuestions=['Has Assignment 2 been extended?','What format should I submit?','What happens if I submit late?'];
function App(){
 const [run,setRun]=useState<Run|null>(null),[input,setInput]=useState(''),[history,setHistory]=useState(readHistory),[prefs,setPrefs]=useState(readPreferences);
 const [drawer,setDrawer]=useState(false),[search,setSearch]=useState(''),[settings,setSettings]=useState(false),[about,setAbout]=useState(false);
 const [page,setPage]=useState(0),[direction,setDirection]=useState('next'),[autoFollow,setAutoFollow]=useState(prefs.follow),[activityOpen,setActivityOpen]=useState(true),[expanded,setExpanded]=useState<number|null>(null),[liveScroll,setLiveScroll]=useState(true),[deleted,setDeleted]=useState<Run|null>(null),[storageError,setStorageError]=useState(false);
 const timers=useRef<ReturnType<typeof setTimeout>[]>([]),feed=useRef<HTMLDivElement>(null),chat=useRef<HTMLDivElement>(null),dialog=useRef<HTMLElement>(null),historyButton=useRef<HTMLButtonElement>(null),settingsBox=useRef<HTMLDivElement>(null),settingsButton=useRef<HTMLButtonElement>(null),runId=useRef<string|null>(null);
 const running=run?.status==='running',visited=visitedSources(run),pageSource=sources[page];
 const clear=()=>{timers.current.forEach(clearTimeout);timers.current=[];};
 useEffect(()=>()=>clear(),[]);
 useEffect(()=>{try{localStorage.setItem(HISTORY_KEY,JSON.stringify(history));setStorageError(false);}catch{setStorageError(true);}},[history]);
 useEffect(()=>{try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(prefs));}catch{setStorageError(true);}},[prefs]);
 useEffect(()=>{if(run)setHistory(h=>[run,...h.filter(r=>r.id!==run.id)].slice(0,40));},[run]);
 useEffect(()=>{
  if(!drawer)return;
  const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setDrawer(false);if(e.key==='Tab'){const nodes=dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(!dialog.current?.contains(document.activeElement)){e.preventDefault();first.focus();}else if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};
  const frame=requestAnimationFrame(()=>dialog.current?.querySelector<HTMLInputElement>('input')?.focus());document.addEventListener('keydown',onKey);
  return()=>{cancelAnimationFrame(frame);document.removeEventListener('keydown',onKey);historyButton.current?.focus();};
 },[drawer]);
 useEffect(()=>{if(!settings)return;const close=(e:PointerEvent)=>{if(!settingsBox.current?.contains(e.target as Node)&&!settingsButton.current?.contains(e.target as Node))setSettings(false);};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){setSettings(false);settingsButton.current?.focus();}};document.addEventListener('pointerdown',close);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',escape);};},[settings]);
 const smooth=():ScrollBehavior=>prefs.motion==='none'||window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth';
 useEffect(()=>{if(liveScroll&&activityOpen&&feed.current)feed.current.scrollTo({top:feed.current.scrollHeight,behavior:smooth()});},[run?.step,activityOpen,liveScroll]);
 useEffect(()=>{if(running&&autoFollow&&visited>0){setDirection('next');setPage(visited-1);}},[visited,autoFollow,running]);
 const cancel=()=>{clear();runId.current=null;setRun(r=>r?.status==='running'?{...r,status:'cancelled'}:r);};
 const archiveCurrent=()=>{if(run?.status==='running'){const stopped={...run,status:'cancelled' as const};setHistory(h=>[stopped,...h.filter(r=>r.id!==run.id)].slice(0,40));}clear();runId.current=null;};
 const reset=()=>{archiveCurrent();setRun(null);setInput('');setPage(0);setExpanded(null);setAutoFollow(prefs.follow);setDrawer(false);setAbout(false);};
 const start=(q:string)=>{
  if(!q.trim()||running)return;clear();const next:Run={id:crypto.randomUUID(),question:q.trim().slice(0,2000),topic:classify(q),status:'running',step:0,createdAt:Date.now()};runId.current=next.id;setRun(next);setInput('');setExpanded(null);setPage(0);setDirection('next');setActivityOpen(true);setLiveScroll(true);setAutoFollow(prefs.follow);setDrawer(false);chat.current?.scrollTo({top:0});
  const finish=next.topic==='unknown'?1:5;
  for(let i=1;i<=finish;i++)timers.current.push(setTimeout(()=>{if(runId.current!==next.id)return;setRun(r=>r?.id===next.id?{...r,step:next.topic==='unknown'?0:i,status:i===finish?'done':'running'}:r);if(i===finish)setActivityOpen(false);},next.topic==='unknown'?700:i*1450));
 };
 const showPage=(n:number)=>{if(n<0||n>=visited)return;setDirection(n<page?'prev':'next');setPage(n);setAutoFollow(false);};
 const cite=(n:number)=>{setExpanded(n);showPage(n);requestAnimationFrame(()=>document.getElementById(`source-${n}`)?.scrollIntoView({behavior:smooth(),block:'nearest'}));};
 const restore=(item:Run)=>{archiveCurrent();setRun(item.status==='running'?{...item,status:'cancelled'}:item);setPage(Math.max(0,visitedSources(item)-1));setInput('');setExpanded(null);setDrawer(false);setActivityOpen(false);setAutoFollow(false);requestAnimationFrame(()=>chat.current?.scrollTo({top:0}));};
 const remove=(item:Run)=>{if(item.id===run?.id){archiveCurrent();setRun(null);setPage(0);}setHistory(h=>h.filter(r=>r.id!==item.id));setDeleted(item.status==='running'?{...item,status:'cancelled'}:item);};
 const changePreferences=(change:Partial<Preferences>)=>{setPrefs(p=>({...p,...change}));if(change.follow!==undefined)setAutoFollow(change.follow);};
 const filtered=history.filter(h=>h.question.toLowerCase().includes(search.toLowerCase()));
 const Citation=({n}:{n:number})=><button className="citation" aria-label={`View citation ${n+1}`} onClick={()=>cite(n)}>{n+1}</button>;
 return <div className={`app motion-${prefs.motion}`}><div className="landscape" aria-hidden="true"/><div className="background-wordmark" aria-hidden="true">ALLABOUT CAMPUS</div>
  <header className="app-header"><a className="brand" href="#" onClick={e=>{e.preventDefault();reset();}}><span className="logo">a.</span><strong>AllAbout <span>Campus</span></strong></a><div className="header-actions"><span className="term">Fall 2026</span><button className={`history-trigger ${drawer?'is-active':''}`} ref={historyButton} aria-expanded={drawer} onClick={()=>{setDrawer(true);setSearch('');setSettings(false);}}><History size={16}/>History{history.length>0&&<span className="count">{history.length}</span>}</button><div className="settings-anchor"><button ref={settingsButton} className="icon-button" aria-label="Motion settings" aria-expanded={settings} onClick={()=>setSettings(!settings)}><SlidersHorizontal size={17}/></button>{settings&&<div className="settings-popover" ref={settingsBox}><div className="popover-heading">Make yourself comfortable</div><span className="setting-label">Page transitions</span><div className="segmented" role="group" aria-label="Page transitions">{(['slide','page','none'] as const).map(m=><button key={m} aria-pressed={prefs.motion===m} onClick={()=>changePreferences({motion:m})}>{m==='page'?'Page turn':m==='slide'?'Slide':'Off'}</button>)}</div><label className="toggle-row"><span>Follow pages as they’re read</span><input type="checkbox" checked={prefs.follow} onChange={e=>changePreferences({follow:e.target.checked})}/></label><p>Reduced-motion preferences are respected.</p></div>}</div><button className="demo-badge" aria-expanded={about} onClick={()=>setAbout(!about)}><i/>Demo</button></div></header>
  {about&&<div className="about"><span>Fictional course and demo pages. The activity feed is simulated; no search engine, GPT, or Steel request is made.</span><button aria-label="Close demo note" onClick={()=>setAbout(false)}><X size={15}/></button></div>}
  <main className="workspace"><section className="chat-panel"><div className="panel-header"><span><MessageSquare size={16}/>Chat / Task</span><button className="icon-button" aria-label="New task" onClick={reset}><Plus size={18}/></button></div><div className="chat-body" ref={chat}>
   {!run?<div className="welcome"><span className="welcome-icon"><BookOpen size={22}/></span><h1>One less thing to figure out.</h1><p>Deadlines, course updates, the small print.<br/>Let’s look through it together.</p><div className="starters">{starterQuestions.map((q,i)=><button className="starter" key={q} style={{animationDelay:`${i*70}ms`}} onClick={()=>start(q)}>{q}<ArrowUpRight size={15}/></button>)}</div><small>Try DEMO101 · a fictional course</small></div>:<div key={run.id} className="conversation"><div className="user-question">{run.question}</div><div className="answer-label"><span className="small-logo">a.</span>AllAbout Campus</div>
    {run.topic!=='unknown'&&<section className={`research ${running?'is-running':''}`}><button className="section-toggle" onClick={()=>setActivityOpen(!activityOpen)} aria-expanded={activityOpen}><span>{running?<LoaderCircle size={15} className="spin"/>:run.status==='cancelled'?<Square size={13}/>:<Check size={15}/>}<span>{running?'Looking through the sources':run.status==='cancelled'?'Research stopped':'Reviewed 3 demo pages'}</span></span><ChevronDown size={15} className={activityOpen?'rotated':''}/></button><div className="research-subline"><span>{running?'Campus search · simulated':`${visited} page${visited===1?'':'s'} opened · demo`}</span>{running&&<span>{run.step+1} / 6</span>}</div><div className="progress-track"><span style={{width:`${run.step/5*100}%`}}/></div><div className={`activity-collapse ${activityOpen?'open':''}`}><div className="activity-collapse-inner"><div className="activity-feed" ref={feed} onWheel={()=>setLiveScroll(false)} onTouchMove={()=>setLiveScroll(false)} tabIndex={0} aria-label="Research activity"><ol>{activity.slice(0,run.step+1).map((a,i)=><li key={`${run.id}-${i}`} className={`activity-item ${i===run.step&&running?'current':''}`}><span className="activity-icon">{i===run.step&&running?<LoaderCircle size={13} className="spin"/>:i===0?<Search size={13}/>:<Check size={13}/>}</span><div>{a.source!==null?<button className="activity-source" onClick={()=>showPage(a.source!)}>{a.title}<ArrowUpRight size={12}/></button>:<span>{a.title}</span>}<small>{a.detail}</small>{a.source!==null&&<span className="source-chip"><Globe size={10}/>Demo page {a.source+1}</span>}</div></li>)}</ol></div>{!liveScroll&&running&&<button className="follow-activity" onClick={()=>setLiveScroll(true)}><ArrowDown size={12}/>Follow activity</button>}</div></div></section>}
    {running?<p className="working" role="status"><span className="typing"><i/><i/><i/></span>{run.topic==='unknown'?'Checking the demo scope…':'Reading, then checking the details.'}</p>:run.status==='cancelled'?<div className="answer"><p>Stopped here. Pick it up whenever you’re ready.</p><button className="retry" onClick={()=>start(run.question)}><RotateCcw size={14}/>Try again</button></div>:<div className="answer" key={`answer-${run.id}`}>
     {run.topic==='deadline'?<><p>Yes — you have until <strong>September 20, 5:00 PM</strong>, Toronto time.<Citation n={1}/></p><p>The instructor extended the September 18 deadline. The submission format stays the same: one PDF.<Citation n={0}/></p><div className="date-update"><del>Sep 18</del><ArrowRight size={15}/><strong>Sep 20</strong><small>5:00 PM · Toronto</small></div></>:run.topic==='format'?<p>Submit your work as <strong>one PDF</strong>. The instructor changed the deadline, but kept the other submission requirements.<Citation n={0}/><Citation n={1}/></p>:run.topic==='late'?<p>These sources don’t mention a late penalty. It’s worth checking with your teaching team before assuming one.</p>:<p>This demo covers DEMO101 Assignment 2. Try asking about the deadline, submission format, or late policy.</p>}
     {run.topic!=='unknown'&&<div className="answer-foot"><Check size={12}/>Checked against the demo sources</div>}
    </div>}
    {run.status==='done'&&run.topic!=='unknown'&&<section className="evidence" id="evidence"><div className="section-label"><span>Sources</span><small>3 pages</small></div>{sources.map((s,i)=><div className={`source ${expanded===i?'selected':''}`} id={`source-${i}`} key={s.title}><button className="source-button" aria-expanded={expanded===i} onClick={()=>{setExpanded(expanded===i?null:i);showPage(i);}}><s.icon size={15}/><span>{s.title}<small>{s.role}</small></span><span className="source-number">{i+1}</span></button><div className={`quote-collapse ${expanded===i?'open':''}`}><div><blockquote>{s.quote}<small>{s.note}</small><button className="view-page" onClick={()=>showPage(i)}>View demo page <ExternalLink size={12}/></button></blockquote></div></div></div>)}</section>}
   </div>}
  </div><div className="composer-wrap"><form onSubmit={e=>{e.preventDefault();start(input);}}><textarea maxLength={2000} aria-label="Ask a question" placeholder="Ask about your course…" rows={2} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();start(input);}}}/><div><span>DEMO101 <span>·</span> Fall 2026</span>{running?<button className="send" type="button" aria-label="Stop task" onClick={cancel}><Square size={14}/></button>:<button className="send" disabled={!input.trim()} aria-label="Send question"><ArrowUp size={18}/></button>}</div></form><p>Demo sources. Real peace of mind comes from checking.</p></div></section>
  <section className="browser-panel"><div className="panel-header"><span><Monitor size={16}/>Steel Live Browser</span><small className="connection"><i/>Not connected</small></div><div className="browser-toolbar"><span className="browser-dots"><i/><i/><i/></span><div className="address"><Globe size={13}/><span>{visited>0?`${pageSource.host}/${pageSource.path.replaceAll(' / ','/')}`:'Waiting for a task'}</span></div><small>DEMO</small></div>
   <div className="browser-stage"><div className="page-underlay" aria-hidden="true"/>{visited===0?<div className="browser-empty"><div className={`window-symbol ${running?'window-loading':''}`}><div><i/><i/><i/></div><span/><span/><span/></div><h2>{running?'Finding a place to start.':'See what we’re looking at.'}</h2><p>{running?'The first demo page will open shortly.':<>Pages appear here as they’re reviewed.<br/>You can turn back through them anytime.</>}</p><small>{run?.topic==='unknown'?'No pages opened for this question.':'A quiet corner for the original sources.'}</small></div>:<article key={`${run?.id}-${page}`} className={`page-preview direction-${direction}`}><div className="preview-school"><BookOpen size={18}/><strong>Campus course desk</strong><span>Demo page {page+1}</span></div><div className="preview-nav">DEMO101 <ChevronRight size={11}/> Fall 2026 <ChevronRight size={11}/> {page===0?'Syllabus':page===1?'Announcements':'Discussion'}</div><span className="document-label">{pageSource.role}</span><h2>{pageSource.title}</h2><div className="document-author">{page===2?'Demo student':'Demo teaching team'} <span>·</span> {pageSource.date}</div><div className="document-copy">{page===0?<><p>Assignment 2 is due <mark>September 18, 2026 at 5:00 PM</mark> (America/Toronto).</p><p>Submit your work as a single PDF.</p></>:page===1?<><p>The deadline for Assignment 2 has been extended to <mark>September 20, 2026 at 5:00 PM</mark> (America/Toronto).</p><p>All other submission requirements remain unchanged.</p></>:<><p>“Last year this assignment felt manageable. I remember handing it in on a Friday.”</p><div className="opinion-note">A student’s experience from last year. This does not change the current course policy.</div></>}</div><div className="page-source-note"><Link2 size={13}/>{pageSource.note}</div><div className="fictional-note">Fictional course · locally rendered preview</div></article>}<span className="panel-watermark" aria-hidden="true">allabout campus.</span></div>
   <div className="page-controls"><div className="page-status">{running?<LoaderCircle size={13} className="spin"/>:<Globe size={13}/>}<span>{running?'Reviewing demo pages':visited>0?'Source pages':'Your sources will appear here'}</span></div><nav className="pagination" aria-label="Source pages"><button className="page-arrow" aria-label="Previous source page" disabled={visited===0||page===0} onClick={()=>showPage(page-1)}><ChevronLeft size={16}/></button><span>{visited?`${page+1} / ${visited}`:'0 / 0'}</span><button className="page-arrow" aria-label="Next source page" disabled={visited===0||page>=visited-1} onClick={()=>showPage(page+1)}><ChevronRight size={16}/></button></nav></div>
   <div className="browser-footer">{running&&!autoFollow?<button onClick={()=>setAutoFollow(true)}><ArrowRight size={12}/>Follow live activity</button>:<span>{running?'Pages follow the demo activity':'Browse at your own pace'}</span>}<span>Simulated browsing</span></div>
  </section></main>
  <footer className="app-footer"><span>ALLABOUT CAMPUS</span><span>Made for the questions between classes.</span></footer>
  {drawer&&<div className="drawer-backdrop" onClick={()=>setDrawer(false)}><aside ref={dialog} className="history-drawer" role="dialog" aria-modal="true" aria-labelledby="history-heading" onClick={e=>e.stopPropagation()}><div className="drawer-heading"><div><History size={18}/><h2 id="history-heading">Your history</h2></div><button className="icon-button" aria-label="Close history" onClick={()=>setDrawer(false)}><X size={18}/></button></div><p className="history-description">A place to pick up where you left off.</p><label className="history-search"><Search size={16}/><input aria-label="Search history" placeholder="Find a past question…" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button aria-label="Clear history search" onClick={()=>setSearch('')}><X size={13}/></button>}</label><div className="history-list">{filtered.length===0?<div className="history-empty"><MessageSquare size={25}/><h3>{search?'No matching questions.':'Nothing here just yet.'}</h3><p>{search?'Try a different word.':'Your inquiries will be saved here on this browser.'}</p></div>:filtered.map(item=><div className={`history-item ${item.id===run?.id?'current':''}`} key={item.id}><button className="history-open" onClick={()=>restore(item)}><MessageSquare size={15}/><span>{item.question}<small>{new Date(item.createdAt).toLocaleDateString('en-CA',{month:'short',day:'numeric'})} · {new Date(item.createdAt).toLocaleTimeString('en-CA',{hour:'2-digit',minute:'2-digit'})} <span>{item.status==='done'?'Completed':item.status==='running'?'In progress':'Stopped'}</span></small></span></button><button className="delete-history" aria-label={`Delete inquiry: ${item.question}`} onClick={()=>remove(item)}><Trash2 size={14}/></button></div>)}</div><div className="history-bottom"><span>{storageError?'Storage unavailable — kept for this session only.':'Saved on this browser · up to 40 inquiries'}</span><small>Opening history restores the result, without a new search.</small></div></aside></div>}
  {deleted&&<div className="toast" role="status"><span>Inquiry removed</span><button onClick={()=>{setHistory(h=>[deleted,...h.filter(r=>r.id!==deleted.id)].slice(0,40));setDeleted(null);}}>Undo</button><button aria-label="Dismiss notification" onClick={()=>setDeleted(null)}><X size={14}/></button></div>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
